name: Testing
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  create:
    branches:
      - "main"
    tags:
      - "**"

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}
    steps:
      # Install stable-pretraining
      - name: Checking Out Repository
        uses: actions/checkout@v2
      # Install Python & Packages
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: which python
      - name: Install dependencies
        run: |
          python -m pip install --user --upgrade --progress-bar off pip
      - name: Install 'stable_pretraining' package
        run: |
          python -m pip install --user -e .[all,dev]
      # Run Tests
      - name: Run Unit Tests
        run: pytest stable_pretraining/ -m unit --verbose --cov=stable_pretraining --cov-report term
      # Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}

  Test-minimal:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}
    steps:
      # Install stable_pretraining
      - name: Checking Out Repository
        uses: actions/checkout@v2
      # Install Python & Packages
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: which python
      - name: Install dependencies
        run: |
          python -m pip install --user --upgrade --progress-bar off pip
      - name: Install 'stable_pretraining' package
        run: |
          python -m pip install --user -e .[all,dev]
      # Run Tests
      - name: Run Unit Tests
        run: pytest stable_pretraining/ -m unit --verbose --cov=stable_pretraining --cov-report term
      # Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
